config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :blogs do
    collection do
      get :list
    end
  end

  resources :my_blogs do
    collection do
      get :test
    end
  end
  resources :categories do
    collection do
    end
  end
  resources :articals
  resources :users

  root :to => "blogs#index"

  resources :logins do
    collection do
      get :logout
    end
  end

  resources :buckets do
    resources :objects
  end

  namespace :admin do
    resources :blogs do
      collection do
        post '/blogs/upload_paste_image_to_cdn', to: 'blogs#upload_paste_image_to_cdn'
      end
    end

  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :categories

  after_save do
#    Category.create name: self.category.try(:name), blog_id: self.id
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    # 找到指定的blogs,  migration,   is_top   默认false,  修改之后是true
    #@top_blogs = Blog.where('is_top = ?', true).order('created_at desc')
    # 找到普通的blogs
    @blogs = Blog.all
    #@blogs = @blogs.where('title like ?', "%#{params[:blog_title]}%") if params[:blog_title].present?
    #@blogs = @blogs.where('content like ?', "%#{params[:blog_content]}%") if params[:blog_content].present?
    @blogs = @blogs.where('content like ? or title like ?', "%#{params[:blog_content]}%", "%#{params[:blog_content]}%") if params[:blog_content].present?
    @total_count = @blogs.all.size
    #@blogs = @blogs.order('created_at desc').page(params[:page]).per(100)
    @blogs = @blogs.order('id desc').page(params[:page]).per(100)
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: '操作成功' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: '操作成功' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: '操作成功' }
      format.json { head :no_content }
    end
  end

  private
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :content, :category_id, :is_top)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<!-- 版心 -->
<script src="//cdn.ckeditor.com/4.18.0/standard/ckeditor.js"></script>
<div class="blog-edit-container">
  <!-- 标题编辑区 -->
  <%= form_for @blog do |form| %>
    <div class="title">
      <label>
        标题:
        <%= form.text_field :title %>
      </label>
      <label>
        类别:
        <%= form.select "category_id", options_from_collection_for_select(Category.all, :id, :name) %>
        没有找到？<%= link_to "点此新建", new_category_path %>
      </label>
    </div>
    <div>
      是否置顶:
      <%= form.select :is_top, options_for_select([['buttom',0], ['top', 1]], params[:is_top]) %>
    </div>
    <!-- 内容编辑区 -->
    <div id="editor">
      <%#= form.text_area :content, size: "170x30" %>
      内容: <%#= form.text_field :content %>
      <%= form.cktext_area :content %>
    </div>

      <%# form.text_area :content, size: "80x80" %>
      <%= form.submit "发布文章", class: 'btn btn-primary btn-sm' %>
  <% end %>
</div>

<script>
  /*
  // Replace the <textarea id="editor1"> with a CKEditor 4
  // instance, using default configuration.
  CKEDITOR.replace( 'blog_content' );
  */
</script>

app/views/blogs/edit.html.erb
<h3>编辑</h3>
<%= link_to raw('返回&gt;&gt;'), blogs_path, class: 'detail1' %>
<%= render 'form' %>

<br/>
<%= link_to '详情', @blog, class: 'detail1' %>

app/views/blogs/index.html.erb
<h3>琳琳的博客</h3>
<p>博客总数: <%= @total_count %></p>
<%= paginate @blogs %>
<%= link_to "新建", new_blog_path if session[:current_user] == "admin" %><br/>
<%= form_tag '', method: :get do %>
  <!--
  <label class="control-label">
    标题
    <i data-toggle="popover" data-togger="hover" data-container='body' data-html='true' title='说明：根据标题内关键词模糊查询' data-content='输入xxxxx' class='fa fa-question-circle' > </i>
    <i data-toggle="popover" data-togger="hover" data-container='body' data-html='true' title='说明：根据文章内关键词模糊查询' data-content='输入xxxxx' class='fa fa-question-circle' > </i>
    <%#= text_field_tag :blog_title, params[:blog_title] %>
  </label>
  -->
  <label class="control-label">
    根据标题或内容模糊查询:
    <%= text_field_tag :blog_content, params[:blog_content] %>
  </label>
  <%= submit_tag raw("&#xf002; 查询"), class: "form_submit", class: 'btn btn-secondary btn-sm fa-input' %>
<% end %>
<!--
<%# @top_blogs.each do |blog| %>
  <a href="/blogs/<%#= blog.id %>" class="title"><%#= blog.id %>  <%#= blog.title %>
  </a></br>
<%# end %>
-->

<br/>

app/views/blogs/new.html.erb
<h3>新建</h3>

<%= render 'form' %>
<br/>
<%= link_to "返回",blogs_path %>

app/views/blogs/show.html.erb
<!-- 右侧区域，显示博客列表 -->
<!-- 使用这个 div 来放博客内容 -->
<div class="blog-content">
  <%= link_to raw('编辑&gt;&gt;'), edit_blog_path(@blog), class: 'detail1'%>
  <!-- 博客的标题 -->
  <h3>
    <%= @blog.title %>
  </h3>
  <!-- 博客的日期 -->
  <div class="date">
    <%= @blog.created_at.strftime('%Y-%m-%d %I:%M%p') %>
  </div>
  <!-- 博客的内容 -->
  <div class="detail-content">
    <%= raw(@blog.content) %>
  </div>
  <%= link_to raw('&lt;&lt;返回'), blogs_path, class: 'detail1'%>
</div>
<style>
.hljs {
  *! background: #fff !important;
}
</style>