config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :blogs do
    collection do
      get :list
    end
  end

  resources :my_blogs do
    collection do
      get :test
    end
  end
  resources :categories do
    collection do
    end
  end
  resources :articals
  resources :users

  root :to => "blogs#index"

  resources :logins do
    collection do
      get :logout
    end
  end

  resources :buckets do
    resources :objects
  end

  namespace :admin do
    resources :blogs do
      collection do
        post '/blogs/upload_paste_image_to_cdn', to: 'blogs#upload_paste_image_to_cdn'
      end
    end

  end

end

app/models/my_blog.rb
class MyBlog < ActiveRecord::Base
end

app/controllers/my_blogs_controller.rb
class MyBlogsController < ApplicationController
  before_action :set_my_blog, only: [:show, :edit, :update, :destroy, :test]

  # GET /my_blogs
  # GET /my_blogs.json

  def test

    @test = MyBlog.where('title = ?', params[:title])
    respond_do |format|
      format.html
      format.json {render json: @test}
  end

  def index
    @my_blogs = MyBlog
    @total_count = MyBlog.all.size
    @my_blogs = @my_blogs.page(params[:page]).per(10)
  end

  # GET /my_blogs/1
  # GET /my_blogs/1.json
  def show
  end

  # GET /my_blogs/new
  def new
    @my_blog = MyBlog.new
  end

  # GET /my_blogs/1/edit
  def edit
  end

  # POST /my_blogs
  # POST /my_blogs.json
  def create
    @my_blog = MyBlog.new(my_blog_params)

    respond_to do |format|
      if @my_blog.save
        format.html { redirect_to @my_blog, notice: 'My blog was successfully created.' }
        format.json { render :show, status: :created, location: @my_blog }
      else
        format.html { render :new }
        format.json { render json: @my_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_blogs/1
  # PATCH/PUT /my_blogs/1.json
  def update
    respond_to do |format|
      if @my_blog.update(my_blog_params)
        format.html { redirect_to @my_blog, notice: 'My blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_blog }
      else
        format.html { render :edit }
        format.json { render json: @my_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_blogs/1
  # DELETE /my_blogs/1.json
  def destroy
    @my_blog.destroy
    respond_to do |format|
      format.html { redirect_to my_blogs_url, notice: 'My blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_blog
      @my_blog = MyBlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_blog_params
      params.require(:my_blog).permit(:title, :content)
    end
end

app/helpers/my_blogs_helper.rb
module MyBlogsHelper
end

app/views/my_blogs/_form.html.erb
<%= form_for(@my_blog) do |f| %>

  <table class='table table-striped table-hover table-bordered'>
    <tr>
      <th style="width: 150px;">
        标题
      </th>
      <td>
        <%= f.text_field :title, class: "form-control" %>
      </td>
    </tr>

    <tr>
      <th>
        内容
      </th>
      <td>
        <%= f.text_field :content , class: "form-control" %>
      </td>
    </tr>
  </table>
  <%= f.submit "确定", class: 'btn btn-primary btn-sm' %>
<% end %>

app/views/my_blogs/edit.html.erb
<h3>编辑</h3>
<%= render 'form' %>

<br/>
<%= link_to '编辑', @my_blog %> |
<%= link_to '返回', my_blogs_path %>

app/views/my_blogs/index.html.erb
<h3>琳琳的博客</h3>

<p>博客总数<%= @total_count %></p>
<br/>
<%= paginate @my_blogs %>
<%= link_to "新建", new_my_blog_path %><br/>

<%= form_tag '', method: :get do %>
  标题: <%= text_field_tag :my_blog_title, params[:my_blog_title] %>
  内容: <%= text_field_tag :my_blog_content, params[:my_blog_content] %>
  <%= submit_tag "查询", class: "form_submit", class: 'btn btn-secondary btn-sm'  %>
<% end %>

<p>如果你点我，我就会消失。</p>
<p>继续点我!</p>
<p>接着点我!</p>
<table class="table table-striped table-bordered">
  <tr>
    <th style="width: 150px;">ID</th>
    <th>标题</th>
    <th>内容</th>
    <th style="width: 150px;">操作</th>
  </tr>
  <% @my_blogs.each do |my_blog| %>
    <tr>
       <!-- <a href="/my_blogs/<%= my_blog.id %>" > <%= my_blog.id %> <%= my_blog.title %> </a>
       -->
      <td>
        <%= my_blog.id %>
      </td>
      <td>
        <%= my_blog.title %>
      </td>
      <td>
        <%= my_blog.content %>
      </td>
      <td>
        <%= link_to "编辑", edit_my_blog_path(:id => my_blog.id) %>
        <%= link_to "删除",my_blog,:method => :delete, class: 'btn btn-danger btn-sm' %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to '返回', my_blogs_path %><br>
<%= link_to '新建', new_my_blog_path %>
<script>
  $(document).ready(function(){
    $("p").click(function(){
      $(this).hide();
    });
  });
</script>

app/views/my_blogs/new.html.erb
<h3>新建页面</h3>

<%= render 'form' %>
<br/>

<%= link_to '返回', my_blogs_path %>

app/views/my_blogs/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-striped table-bordered">
  <% @my_blog.each do |my_blog| %>
    <tr>
      <th>标题</th>
      <th style="width:150px;">操作</th>
      <td >
        <%= @my_blog.title %>
      </td>
    </tr>
    <tr>
      <th>内容</th>
      <td>
        <%=my_blog.content %>
      </td>
      </th>
    </tr>
</table>

<%= link_to '编辑', edit_my_blog_path(@my_blog) %> |
<%= link_to '返回', my_blogs_path %>