config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :blogs do
    collection do
      get :list
    end
  end

  resources :my_blogs do
    collection do
      get :test
    end
  end
  resources :categories do
    collection do
    end
  end
  resources :articals
  resources :users

  root :to => "blogs#index"

  resources :logins do
    collection do
      get :logout
    end
  end

  resources :buckets do
    resources :objects
  end

  namespace :admin do
    resources :blogs do
      collection do
        post '/blogs/upload_paste_image_to_cdn', to: 'blogs#upload_paste_image_to_cdn'
      end
    end

  end

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/articles_controller.rb
class ArticalsController < ApplicationController
  before_action :set_artical, only: [:show, :edit, :update, :destroy]

  # GET /articals
  # GET /articals.json
  def index
    @articals = Artical.all

    @articals = @articals.where('title like ? ', "%#{params[:artical_title]}%") if params[:artical_title].present?
    @articals = @articals.where('content like ? ', "%#{params[:artical_content]}%") if params[:artical_content].present?

    @total_count = @articals.all.size
    @articals = @articals.page(params[:page]).per(3)
  end

  # GET /articals/1
  # GET /articals/1.json
  def show
  end

  # GET /articals/new
  def new
    @artical = Artical.new
  end

  # GET /articals/1/edit
  def edit
  end

  # POST /articals
  # POST /articals.json
  def create
    @artical = Artical.new(artical_params)

    respond_to do |format|
      if @artical.save
        format.html { redirect_to @artical, notice: 'Artical was successfully created.' }
        format.json { render :show, status: :created, location: @artical }
      else
        format.html { render :new }
        format.json { render json: @artical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articals/1
  # PATCH/PUT /articals/1.json
  def update
    respond_to do |format|
      if @artical.update(artical_params)
        format.html { redirect_to @artical, notice: 'Artical was successfully updated.' }
        format.json { render :show, status: :ok, location: @artical }
      else
        format.html { render :edit }
        format.json { render json: @artical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articals/1
  # DELETE /articals/1.json
  def destroy
    @artical.destroy
    respond_to do |format|
      format.html { redirect_to articals_url, notice: 'Artical was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artical
      @artical = Artical.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artical_params
      params.require(:artical).permit(:content, :titile)
    end
end

app/views/articles/_form.html.erb
<%= form_for @artical do |form| %>
  <table class='table table-striped table-hover table-bordered'>
    <tr>
      <th style="width: 150px;">
        标题
      </th>
      <td>
        <%= form.text_field :titile ,class: "form-control" %> </td>
      </td>
    </tr>
    <tr>
      <th>
        内容
      </th>
      <td>
        <%= form.text_area :content ,class: "form-control" %>
    </tr>
  </table>
  <%= form.submit "确定", class: 'btn btn-primary' %>
<% end %>

app/views/articles/edit.html.erb
<h3>编辑</h3>
<%= render 'form' %>

<%= link_to '详情', @artical %> |
<%= link_to '返回', articals_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>列表</h1>
文章总数 <%= @total_count %>
<%= paginate @articals %>

<%= form_tag '', method: :get do %>
  题目: <%= text_field_tag :artical_title, params[:artical_title] %>
  内容: <%= text_field_tag :artical_content, params[:artical_content] %>
  <%= submit_tag nil, class: "form_submit" %>
<% end %>
 <%= link_to '新建', new_artical_path %>
<table class='table table-striped table-hover table-border'>
  <thead>
    <tr>
      <th>标题</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articals.each do |artical| %>
      <tr>
        <td><%= artical.titile %></td>
        <td>
          <%= artical.content %>
        </td>
        <td><%= link_to '详情', artical %></td>
        <td><%= link_to '编辑', edit_artical_path(artical) %></td>
        <td><%= link_to '删除', artical, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/articles/new.html.erb
<h3>新建</h3>

<%= render 'form' %>
<br/>
<%= link_to '返回', articals_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<table>
<tr>
  <th style="width:150px;">
    标题
  </th>
  <td>
    <%= @artical.titile %>
  </td>
  <td>
  </td>
</tr>
<tr>
  <th>
    内容
  </th>
  <td>
    <%= @artical.content %>
  </td>
  <td>
  </td>
</tr>
</table>

<br/>
<%= link_to '编辑', edit_artical_path(@artical) %> |
<%= link_to '返回', articals_path %>